version: '3.8'

services:
  web:
    build: .
    container_name: bca_notes_api
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    # The container will restart if it crashes, but not if you stop it manually
    restart: on-failure